### PR TITLE
FIX #617, auto join, collection & tabs, #1035

### LINKED ISSUE #617: Switch position is not updated properly in case changing setting
**Describe the bug**
This is a UI bug, switch position does not update right when I click on the switch, there is some latency, but the setting is applied.

**To Reproduce**
1. Go to Collaborators menu
2. Press 3-dots-button for any collaborator in the list
3. Try toggling switches in this tab

**Expected behavior**

**Screenshots**
errorSwitch

### PR DESCRIPTION
**Pull request by BenoitTallandier**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added the Signed-off-by statement at the end of my commit message.

### CODE REVIEW

File: twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js [hunk 1]
```diff
@@ -19,6 +19,31 @@ import Members from 'app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspaceP
 import Tabs from 'components/Tabs/Tabs.js';
 import InitService from 'app/services/InitService';
 import ConsoleService from 'app/services/Console/ConsoleService';
+import { Switch } from 'antd';
+
+class AdminSwitch extends Component {
```
Comment (chamerling) [inline twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js:24]: We now use functional components for all our new components

File: twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js [hunk 2]
```diff
@@ -145,30 +170,25 @@ export default class WorkspacePartner extends Component {
...
+          col={col}
+          adminLevelId={adminLevelId}
+          onChange={state =>
+            this.confirmIfMe(
+              col.user.id,
+              {
+                text: Languages.t(
+                  'scenes.app.popup.workspaceparameter.pages.modify_level',
+                  [],
+                  "Modifier votre niveau d'accès à l'entreprise ? (cette action n'est pas réversible si vous réduisez vos droits d'accès)",
```
Comment (chamerling) [inline twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspacePartner.js:183]: You should put the default in `en`

**Review by chamerling — CHANGES_REQUESTED** [review]

**Review by chamerling — APPROVED** [review]
