### PR TITLE
🌟 Feature/messages node step 3 + general service + clean code

### LINKED ISSUE #1175: No notification for first message in a direct channel (probably that badge try to be created before user is in the channel)
#### Describe the bug
When I start a new direct discussion with someone by sending the first message, the other user is not notified with a badge.

#### To Reproduce
- Open a new direct discussion
- Send the first message
- Go on the other account
- You won't see the badge

#### Screenshots
https://user-images.githubusercontent.com/22451567/118807606-cee40a80-b8a8-11eb-871d-e08d691d8e42.mov

### LINKED ISSUE #1316: Move version to config/default.json or config/version.json
https://github.com/linagora/Twake/pull/1285#discussion_r639683493

### PR DESCRIPTION
**Pull request by RomaricMourgues**
- [x] Create a core service for search with a adpater system to works with both mongodb or elasticsearch
- [x] Implement push to es with buffer
- [x] Retro-compatibility of PHP apis (send, get messages in channel)
- [x] Retro-compatibility of PHP apis (edit message, react, delete, get in thread)
- [x] Move php code that manage push notifications
- [x] Move activity message consumer to node
- [x] Move php code that trigger notifications from php to node... to node
- [x] Fix #1175  
- [x] Fix #1316 
- [ ] Next PR: Check applications still works with php api forwarded to node
- [ ] Next PR: Convert maximum possible Twacode <-> Blocks
- [ ] Next PR: Implement search format for ES (based on mongo API)
- [ ] Next PR: Add elasticsearch tests

### CODE REVIEW

File: twake/backend/node/src/services/notifications/services/mobile-push/service.ts [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+          click_action: "FLUTTER_NOTIFICATION_CLICK",
+        },
+        collapse_key: message.channel_id,
+        registration_ids: [deviceIdentifier],
+      };
+
+      //Push to fcm
+      try {
+        const response = await (
+          await fetch(firebaseEndpoint, {
```
Comment (chamerling) [inline twake/backend/node/src/services/notifications/services/mobile-push/service.ts:64]: You may not need to await for it. Pretty sure that there is a NPM module which provides a bulk API or something like this.

File: twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts [hunk 2]
```diff
@@ -164,6 +160,11 @@ export class CassandraConnector extends AbstractConnector<
       return this;
     }
 
+    if (this.options.elasticsearch) {
```
Comment (chamerling) [inline twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts]: Is it up to the ORM to manage elasticsearch?

Here is what I was thinking about the search: Create a `@Index` decorator and put it everywhere we want to index resources. The search is a separated core service which has nothing to deal with ORM.

File: twake/backend/node/src/services/general/constants.ts [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+  availables: ["en", "fr", "es", "vn", "ru"],
+};
+
+export const version: ServerConfiguration["version"] = {
+  current: /* @VERSION_DETAIL */ "2021.Q2.505",
+  minimal: {
+    web: /* @MIN_VERSION_WEB */ "2021.Q1.481",
+    mobile: /* @MIN_VERSION_MOBILE */ "2021.Q1.385",
+  },
+};
```
Comment (chamerling) [inline twake/backend/node/src/services/general/constants.ts:14]: Why don't we put this in the configuration file?

Comment (RomaricMourgues) [reply twake/backend/node/src/services/general/constants.ts:14]: Because this is not configuration but directly related to the code itself (the version of the backend). If I put it in configuration we'll need to change it manually on each update.

File: twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts (hunk 2 above)
Comment (RomaricMourgues) [reply twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts]: I first though like you, then I though that I want mongodb installs to work without elasticsearch (using regex calls). This is why I decided to move it in the ORM in a way to "extends" the scylladb capabilities.
I created an extension of the decorator @entity decorator, to choose what to index or not at the upsert time.
We can address this tomorrow in daily?

File: twake/backend/node/src/services/notifications/services/mobile-push/service.ts (hunk 1 above)
Comment (RomaricMourgues) [reply twake/backend/node/src/services/notifications/services/mobile-push/service.ts:64]: Yes and no, currently the few APIs I found are marked as depreciated because Google has its own. And I through we would not like to have the whole firebase library in our code, what do you think?

Comment (RomaricMourgues) [reply twake/backend/node/src/services/notifications/services/mobile-push/service.ts:64]: I don't remember if I let the Fixme comment or not about the fact that we need a proper service to handle it with bulk mode someday, on that part I totally agree +1

File: twake/backend/node/src/services/general/constants.ts (hunk 3 above)
Comment (RomaricMourgues) [reply twake/backend/node/src/services/general/constants.ts:14]: We can put it in default.json or version.json (it will not be changed by administrator)

File: twake/backend/node/src/services/notifications/services/mobile-push/service.ts (hunk 1 above)
Comment (RomaricMourgues) [reply twake/backend/node/src/services/notifications/services/mobile-push/service.ts:64]: Move it to platform service

File: twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts (hunk 2 above)
Comment (RomaricMourgues) [reply twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts]: I will move it to platform service

**Comment by RomaricMourgues** [comment]
@chamerling I will not continue on this PR as it becomes monstruosly big. Can I merge it and let you comment on it after it is merged ?

**Comment by chamerling** [comment]
Good for me
